### ISSUE TITLE
Release: Sep 23, 2020

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#1331]
Branches to be merged to master.

**Comment by melwong-jcc** [comment]
If the production Flickr album is available by tomorrow, will deploy [feature/WSGEN-1046-1051--flickr-mosaic](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1046-1051--flickr-mosaic) to 20200922 branch

**Comment by ivanbueno-jcc** [comment]
feature/WSGEN-1081--email-subject-signature

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1087-1084-1085--css-fixes](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1087-1084-1085--css-fixes)

**Comment by nelsonwong-jcc** [comment]
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1073--Newsroom-Access-Unpublished #

**Comment by nelsonwong-jcc** [comment]
[feature/WSGEN-1073--Newsroom-Access-Unpublished](url)

**Comment by nelsonwong-jcc** [comment]
feature/WSGEN-1073--Newsroom-Access-Unpublished
