### ISSUE TITLE
Release : sep 30, 2020

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#1348]

**Comment by baptisten** [comment]
[feature/WSGEN-1077--locations](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1077--locations)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1093--import-madera-forms](https://github.com/JudicialCouncilOfCalifornia/trialcourt/commit/6cbe09d6dd80770f3e3605e041cabeec8947f8be)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1095--sendgrid-categories](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1095--sendgrid-categories)

**Comment by nelsonwong-jcc** [comment]
[hotfix/WSGEN-1080--mobile-logo-not-linking-to-home](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/WSGEN-1080--mobile-logo-not-linking-to-home)

**Comment by nelsonwong-jcc** [comment]
[feature/WSGEN-1082--Enable-Sitemap](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1082--Enable-Sitemap)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1094--map-embeddable](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1094--map-embeddable)
* might cause conflict

**Comment by baptisten** [comment]
[WSGEN-1087-header-footer-patternlab](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/WSGEN-1087-header-footer-patternlab)

**Comment by nelsonwong-jcc** [comment]
[feature/WSGEN-1082--Enable-Sitemap](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1082--Enable-Sitemap)

**Comment by baptisten** [comment]
https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/1380
