### ISSUE TITLE
Release: Dec 2, 2020

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#1579]

**Comment by nelsonwong-jcc** [comment]
[feature/WSGEN-1163--Search-Autocomplete-Authenticated-User](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1163--Search-Autocomplete-Authenticated-User)

**Comment by baptisten** [comment]
[WSGEN-1167-dont-send-digest-other-than-live](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/WSGEN-1167-dont-send-digest-other-than-live
)
