### ISSUE TITLE
Release: Dec 9th 2020

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#1591]

**Comment by baptisten** [comment]
[feature/WSGEN-1140-boost-date-on-search](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1140-boost-date-on-search)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1162--jcart-facets](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1162--jcart-facets)

**Comment by baptisten** [comment]
[feature/WSGEN-1160-teaser-test-in-case-summary](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1160-teaser-test-in-case-summary)

**Comment by baptisten** [comment]
[feature/WSGEN-1155--newsroom-order-of-newlinks](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1155--newsroom-order-of-newlinks)

**Comment by melwong-jcc** [comment]
[feature/WSGEN-1036--archive-newslinks](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1036--archive-newslinks)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1171--jcart-logo](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1171--jcart-logo)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1064--footer-aria-label](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/)

Actually for WSGEN-1164. Branch misnamed with wrong JIRA ID.

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1165--gtm-iframe](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1165--gtm-iframe)
