### ISSUE TITLE
Release: Dec 16th 2020

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1611]

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1173-1174-1175--acc-searchfield-alertheading-textcolor](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1173-1174-1175--acc-searchfield-alertheading-textcolor)

**Comment by baptisten** [comment]
[feature/WSGEN-1147-logging-for-sent-emails](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1147-logging-for-sent-emails)

**Comment by nelsonwong-jcc** [comment]
[feature/WSGEN-1181--GTM-for-Madera](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1181--GTM-for-Madera)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1169--uswds-2.9](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1169--uswds-2.9)

**Comment by melwong-jcc** [comment]
[feature/WSGEN-1178--simplify-tagline-instructions](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1178--simplify-tagline-instructions)
