### ISSUE TITLE
Release: Dec 23rd, 2020

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#1625]

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1183--acc-skip2main](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1183--acc-skip2main)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1184--acc-multiplearticles](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1184--acc-multiplearticles)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1185--acc-redundant-aria](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1185--acc-redundant-aria)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1191--disable-2fa-webservices](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1191--disable-2fa-webservices)

**Comment by baptisten** [comment]
[feature/WSGEN-1182-hide-view-header-on-paged-newslink-view](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1182-hide-view-header-on-paged-newslink-view)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1192--acc-more-contrast-fixes](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1192--acc-more-contrast-fixes)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1190--extra-home-links](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1190--extra-home-links)

**Comment by baptisten** [comment]
https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/1648
