### ISSUE TITLE
Release: Jan 13, 2021

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1651]

**Comment by baptisten** [comment]
[feature/WSGEN-1172-messaging-center](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1172-messaging-center)

**Comment by baptisten** [comment]
[feature/WSGEN-1179-sorting-dashboards](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1179-sorting-dashboards)

**Comment by ivanbueno-jcc** [comment]
[bugfix/lock-composer-version](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/lock-composer-version)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1199--remove-featured-news-attachment](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1199--remove-featured-news-attachment)
