### ISSUE TITLE
Release: Jan 20, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#1667]

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1208--allow-multiple-references-same-title](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1208--allow-multiple-references-same-title)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1196--acc-darkbackbg-contrast-fix](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1196--acc-darkbackbg-contrast-fix)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1209--news-taxonomy-null](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1209--news-taxonomy-null)

**Comment by ivanbueno-jcc** [comment]
[security/20210120](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/security/20210120)
