### ISSUE TITLE
Release: February 10, 2021

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#1687]

**Comment by melwong-jcc** [comment]
Skipping Feb 3 since no changes occurred other than a hot fix the following day.

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1223--hero-image-fill-regression](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1223--hero-image-fill-regression)

**Comment by baptisten** [comment]
[feature/WSGEN-1228-newsroom-edits](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1228-newsroom-edits)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1224--card-title-character-limit](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1224--card-title-character-limit)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-335--remove-azure-in-footer](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-335--remove-azure-in-footer)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-330--remove-translation-links-in-footer](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-330--remove-translation-links-in-footer)
