### ISSUE TITLE
Release: February 17, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#1715]

**Comment by baptisten** [comment]
[feature/TC-337-change-location-icon-color](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-337-change-location-icon-color)

**Comment by baptisten** [comment]
[feature/TC-339-madera-hide-bottom-nav-on-book-pages](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-339-madera-hide-bottom-nav-on-book-pages)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-347--courtyard-increase-menu-font](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-347--courtyard-increase-menu-font)
