### ISSUE TITLE
Release: February 24, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#1732]

**Comment by sleepingmonk** [comment]
feature/TCI-63--refactor-theme-for-new-artifact

PR to Master https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/1739

There will be conflicts with the Installation Cleanup branch: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/1727

In jcc_base.info.yml keep the updated `components: namespaces:` from that branch, but update the paths to include `1.x` from this branch.

**Comment by ivanbueno-jcc** [comment]
Calvin's: feature/TCI-8--installation-cleanup

**Comment by ivanbueno-jcc** [comment]
[feature/TC-354--madera-domain](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-354--madera-domain)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-361--news-alias-pattern](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-361--news-alias-pattern)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-365--search-forms-title](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-365--search-forms-title)
