### ISSUE TITLE
Release: March 3, 2021

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1747]

**Comment by baptisten** [comment]
[feature/TC-339-book-nav-on-landing-pages](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-339-book-nav-on-landing-pages)

**Comment by melwong-jcc** [comment]
[bugfix/TC-359--aside-hrule-alignment](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/TC-359--aside-hrule-alignment)

**Comment by melwong-jcc** [comment]
[bugfix/TC-369--footer-branding](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/TC-369--footer-branding)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-339-book-nav-on-landing-pages](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-339-book-nav-on-landing-pages)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-367--missing-courtyard-fonts](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-367--missing-courtyard-fonts)

**Comment by ivanbueno-jcc** [comment]
[feature/TC-368--reduce-padding-local-forms](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-368--reduce-padding-local-forms)

**Comment by melwong-jcc** [comment]
[bugfix/TC-370--secondary-footer-cols](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/TC-370--secondary-footer-cols)

**Comment by baptisten** [comment]
[hotfix/cron-newsletter-fix](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/cron-newsletter-fix)

**Comment by baptisten** [comment]
[feature/WSGEN-1232-date-format-on-calendar](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1232-date-format-on-calendar)

**Comment by melwong-jcc** [comment]
[hotfix/WSGEN-1238--for-media-plus-webform-update](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/WSGEN-1238--for-media-plus-webform-update)
[hotfix/WSGEN-1236--media-directories-edit](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/WSGEN-1236--media-directories-edit)
