### ISSUE TITLE
Release: April 1, 2021

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1805]

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1241--rss-footer-placement](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1241--rss-footer-placement)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1200-1220--acc--hat-and-button-focus](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1200-1220--acc--hat-and-button-focus)

**Comment by melwong-jcc** [comment]
[bugfix/TC-382-383--acc--sidenav-heading-and-unused-footer-links](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/TC-382-383--acc--sidenav-heading-and-unused-footer-links)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1242--screenreader-hidden-links](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1242--screenreader-hidden-links)
