### ISSUE TITLE
May 5, 2021

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1847]

**Comment by baptisten** [comment]
[feature/WSGEN-1255-search-improvments](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1255-search-improvments)

**Comment by nelsonwong-jcc** [comment]
@baptisten is the WSGEN-1255 okay to go on May 5th?

**Comment by baptisten** [comment]
Yes, it is not urgent.

**Comment by baptisten** [comment]
[feature/enable-live-webservices](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/enable-live-webservices)

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1265--replace-footer-heading](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1265--replace-footer-heading)
