### ISSUE TITLE
May 12, 2021

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#1864]

**Comment by melwong-jcc** [comment]
[bugfix/WSGEN-1266--footer-shoe-bug](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/WSGEN-1266--footer-shoe-bug)

**Comment by ivanbueno-jcc** [comment]
[hotfix/jcart-migrate](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/jcart-migrate)

**Comment by ivanbueno-jcc** [comment]
[security/20210512](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/security/20210512)
