### ISSUE TITLE
Release: July 28, 2021

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2047]

**Comment by baptisten** [comment]
[feature/TCI-502-webform-styling-fixes](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-502-webform-styling-fixes)
(Courtyard may be slighlty outdated)

**Comment by baptisten** [comment]
SRL : 
[feature/SRL-485-responsive-css](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-485-responsive-css)
