### ISSUE TITLE
Release: August 4, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2060]

**Comment by ivanbueno-jcc** [comment]
[feature/jcart-section-search](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/jcart-section-search)

[feature/WSGEN-1276--unstemmed-autocomplete-solr](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1276--unstemmed-autocomplete-solr)

**Comment by melwong-jcc** [comment]
[feature/SC-42--homepage-latest-news](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-42--homepage-latest-news)

**Comment by baptisten** [comment]
[feature/newsroom-editable-related-news](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/newsroom-editable-related-news)

**Comment by baptisten** [comment]
[feature/tmgmt-auto-accept-translations](https://github.com/chapter-three/jcc-srl/tree/feature/tmgmt-auto-accept-translations)
