### ISSUE TITLE
Release: August 4, 2021 - C3

### ISSUE THREAD

**Issue by arlina-espinoza** [JudicialCouncilOfCalifornia/trialcourt#2075]
Submit PRs to `deployment/20210804-C3` branch.

**Comment by baptisten** [comment]
[feature/tmgmt-auto-accept-translations](https://github.com/chapter-three/jcc-srl/tree/feature/tmgmt-auto-accept-translations)

**Comment by arlina-espinoza** [comment]
-  #2081
- #2076
