### ISSUE TITLE
Release: August 11, 2021

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2083]

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1285--document-fix-related-links](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1285--document-fix-related-links)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1282--subsection-search](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1282--subsection-search)

**Comment by ivanbueno-jcc** [comment]
[feature/storefront-logo](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/storefront-logo)

**Comment by baptisten** [comment]
[feature/TC-block-editing-permission-exception](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TC-block-editing-permission-exception)

**Comment by melwong-jcc** [comment]
**SRL**
[bugfix/SRL-488--missing-accordion-bottom-spacing](https://github.com/chapter-three/jcc-srl/tree/bugfix/SRL-488--missing-accordion-bottom-spacing)

**Comment by ivanbueno-jcc** [comment]
[hotfix/remove-old-madera-from-deployment](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/remove-old-madera-from-deployment)

**Comment by nelsonwong-jcc** [comment]
[feature/SC-44-Implement-Footer](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-44-Implement-Footer)
