### ISSUE TITLE
Release: August 18, 2021 

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2104]

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1286--import-users](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1286--import-users)

**Comment by melwong-jcc** [comment]
[feature/SC-42--local-content-news-homepage-stream](feature/SC-42--local-content-news-homepage-stream)

**Comment by baptisten** [comment]
SRL:
[feature/SRL-491-json-rest-ui](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-491-json-rest-ui)
[feature/SRL-496-dynamic-translate-button](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-496-dynamic-translate-button)

**Comment by ivanbueno-jcc** [comment]
[tooling/db-sync](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/tooling/db-sync)

**Comment by nelsonwong-jcc** [comment]
[feature/SC-128--add-60-40-card-option-for-SC-config](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-128--add-60-40-card-option-for-SC-config)
