### ISSUE TITLE
Release: September 8, 2021 deployment 

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2153]

**Comment by melwong-jcc** [comment]
[feature/SC-109--pro-theme-news-events](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-109--pro-theme-news-events)

**Comment by baptisten** [comment]
SRL : 
[feature/SRL-499-tables-from-courtyard-2x](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-499-tables-from-courtyard-2x)

**Comment by ivanbueno-jcc** [comment]
[feature/JCART--primary-remote-attachment](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/JCART--primary-remote-attachment)
