### ISSUE TITLE
Release: September 15, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2160]

**Comment by melwong-jcc** [comment]
**SRL:**
[bugfix/SRL-508--deployment-deletes-sendgrid-key](https://github.com/chapter-three/jcc-srl/tree/bugfix/SRL-508--deployment-deletes-sendgrid-key)

**Comment by melwong-jcc** [comment]
[feature/SC-157--left-nav](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-157--left-nav)

**Comment by ivanbueno-jcc** [comment]
[feature/WSGEN-1290--add-guid-to-ical](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1290--add-guid-to-ical)

**Comment by ivanbueno-jcc** [comment]
[security/20210915](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/security/20210915)

**Comment by ivanbueno-jcc** [comment]
Release Notes
* SRL
    * update courtyard
    * Content template update
    * bug fixes
    * security updates
* Supreme Court
    * left nav component
    * security updates
* JCart
    * Exchange360 calendar integration
    * security updates  

Details:
* https://github.com/JudicialCouncilOfCalifornia/trialcourt/issues/2160
* https://www.drupal.org/sa-core-2021-010
