### ISSUE TITLE
Release: September 22, 2021

### ISSUE THREAD

**Issue by nelsonwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2174]

**Comment by ivanbueno-jcc** [comment]
[feature/jcart-calendar](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/jcart-calendar)

**Comment by melwong-jcc** [comment]
[bugfix/SC-170--left-nav-not-contextual](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-170--left-nav-not-contextual)

**Comment by ivanbueno-jcc** [comment]
### Release Notes

#### JCART

* Calendar bug fix
* Restrict all content. Redirect anonymous to login page.
* Enable sendgrid
* Reformat description in Calendar export
* Migrate additional 200 remote docs

#### Supreme Court

* Migrate Supreme Court documents. Redirect old url to new.
* Left nav bug fix

#### Security (Global)

* Security update for search_api_attachments
