### ISSUE TITLE
Release: September 29, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2189]

**Comment by melwong-jcc** [comment]
[bugfix/SC-160--logo-not-responsive](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-160--logo-not-responsive)

**Comment by baptisten** [comment]
[feature/SC-168-intro-banner](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-168-intro-banner)

**Comment by melwong-jcc** [comment]
[feature/SC-175--finalize-landing-page-updates](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-175--finalize-landing-page-updates)

**Comment by baptisten** [comment]
[feature/SC-35-alerts-styling](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-35-alerts-styling)

**Comment by ivanbueno-jcc** [comment]
### Supreme Court
[feature/SC-171--subpage-migration](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-171--subpage-migration)
Migrate subpages, create redirects for old urls.

**Comment by melwong-jcc** [comment]
[bugfix/SC-177--masthead-color-not-inheriting](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-177--masthead-color-not-inheriting)

**Comment by nelsonwong-jcc** [comment]
[feature/SC-188--courtyard-composer-update](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-188--courtyard-composer-update)
