### ISSUE TITLE
Release: November 3d, 2021

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2319]

**Comment by baptisten** [comment]
**SC**
[tree/feature/SC-222-bulk-document-importer](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-222-bulk-document-importer)

**Comment by melwong-jcc** [comment]
### SRL
[feature/SRL-523--module-maintenance](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-523--module-maintenance)
- LinkIt Updated
- Robotstxt removed and no longer an option

[feature/SRL-525--print-share-basic-page](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-525--print-share-basic-page)
- Print and share component added to basic pages
