### ISSUE TITLE
Release: December 1, 2021

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2361]

**Comment by baptisten** [comment]
**SC**
[tree/feature/SC-133-accordions-styling](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-133-accordions-styling)
- updated courtyard with pro version of accordions

**Comment by melwong-jcc** [comment]
[bugfix/SC-268--card-image-radius-not-consistent](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-268--card-image-radius-not-consistent)
- Courtyard v262 with radius fix for background images with no color overlay
