### ISSUE TITLE
Riverside: Time-dependent Web Chats

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2418]
The visibility of the embedded web chats on the current Riverside website can be configured based on time.  For example, the Traffic Web Chat is only available between 7am-2pm, while the Jury Web Chat is available from 8am-2pm.

**Comment by ivanbueno-jcc** [comment]
Instead of a custom module, one possible solution is to take advantage of the time-dependent triggers on Google Tag Manager.

The platform utilizes GTM to inject some 3rd party scripts on the page.  For example, here's Alameda's Web Chat:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/56043671/148135821-25ef500b-26ac-45cc-b92d-b80e384af2e4.png">

It may be possible to schedule when a tag can fire:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/56043671/148137678-39fa91b4-0594-400e-a7d4-2dbd5be1f6ac.png">

Or create a javascript variable that returns the day and time, and use that as trigger.
<img width="850" alt="image" src="https://user-images.githubusercontent.com/56043671/148137920-190670d4-1ae2-4ff7-9af4-00d9b8958a3f.png">

**Comment by j-youngberg** [comment]
Update on this issue: we are switching chat vendors and serendipitously, the new chat application will include all of the time dependency within the application. It will no longer require my custom overlay :). We will still need to configure it within GTM as described above, but it will no longer need the time/scheduling element.
