### ISSUE TITLE
Local Environment Setup

### ISSUE THREAD

**Issue by j-youngberg** [JudicialCouncilOfCalifornia/trialcourt#2527]
Greetings, 
    I am attempting to setup the local environment, & have successfully installed Lando & docker. If I attempt to run the site I get the following php require error:
![php require error](https://user-images.githubusercontent.com/100648284/157319552-6620c59c-2a45-421b-9752-cf03696aced5.png)
Then if I run lando composer install or update to attempt to fix it I get errors there as well. If anyone can assist that would be greatly appreciated. Thanks!
![composer core error](https://user-images.githubusercontent.com/100648284/157319853-0ebf5a73-1923-425e-94dd-b331027fb807.png)

**Comment by ivanbueno-jcc** [comment]
@j-youngberg can you delete the following folders:
* vendor
* web/libraries
* web/core

Then try `lando composer install` again.  See if you get the same error.

**Comment by ivanbueno-jcc** [comment]
@j-youngberg "could not delete" seems like a permission issue.  I'm going to loop in the developers from Alameda if they encountered this.  They have the same local environment as you.

**Comment by j-youngberg** [comment]
@ivanbueno-jcc Thank you Ivan - indeed it does. Odd that this is happening even with an elevated PowerShell instance - but not impossible, in fact that may be it - I may need to specify that PowerShell has read/write (and with them delete) permissions or something...
![image](https://user-images.githubusercontent.com/100648284/157341122-8acb037d-95c4-44f8-823f-1d205fa8f40a.png)
