### ISSUE TITLE
Question: Code Dev to Deployment Workflow - Riverside Site

### ISSUE THREAD

**Issue by j-youngberg** [JudicialCouncilOfCalifornia/trialcourt#2533]
What would the steps or workflow/approval process be for us to deploy custom code or Drupal modules to the new site? 
Would you be able to provide a flowchart of the process?

**Comment by ivanbueno-jcc** [comment]
@j-youngberg @samli000 

Here's the deployment workflow in a nutshell:

1. Create a ticket here in Github.  List the requirements.  Discuss the details.  A JCC developer will be assigned to your case.
2. Get latest on the master branch, and create a feature branch using this naming convention:
    ```git checkout -b feature/G-[TICKET-NO]--Description```
    
    For example, if this thread is a ticket, the branch name would be feature/G-2533--Code-Deployment-Workflow
3. Develop and test on the feature branch locally.
4. Push the branch to repo when complete.
    ```git push origin feature/G-2533--Code-Deployment-Workflow```
5. Create a Pull Request to the ```develop``` branch here: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pulls
6. When the checks are complete, Merge to the develop branch.
7. When the deployment is complete, review your feature in the dev server: https://develop-jcc-[trialcourt-name].pantheonsite.io
8. Go back to the ticket, and tag the assigned JCC Developer for review.
9. When the feature passes the review, create a Pull Request to stage.
10. Merge to stage, and send the link to stakeholders for review: https://stage-jcc-[trialcourt-name].pantheonsite.io
11. When it passes review, add your feature to the Release ticket.  Look for an issue tagged with "Deployment".  For example, https://github.com/JudicialCouncilOfCalifornia/trialcourt/issues/2544
      a. Add a link to your feature
      b. Add description in layperson's terms
12.  The developer in rotation will deploy your feature to master on Wednesdays, 2:30pm.

**Comment by j-youngberg** [comment]
Thank you Ivan for this detailed response. This is very helpful :)
