### ISSUE TITLE
Release: May 11th, 2022

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2626]

**Comment by baptisten** [comment]
### SRL
[feature/SRL-591-bug-with-translation-on-pages-with-switchboards](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-591-bug-with-translation-on-pages-with-switchboards)
- Bug with translation on pages with Switchboards

**Comment by baptisten** [comment]
### Newsroom
[feature/WSGEN-1318-newsroom-add-related-links-into-newslinks-digest](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1318-newsroom-add-related-links-into-newslinks-digest)
- Add Related Links Into NewsLinks Digest
