### ISSUE TITLE
Release: Sep 7th, 2022

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2773]

**Comment by sleepingmonk** [comment]
Not sure how you use this Release issue rather than PRs to a release branch, so I guess I'll just put a link to the branch in a comment?
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/TCI-928--node-access-view-cache

**Comment by melwong-jcc** [comment]
This branch is already on Stage so not resetting Stage to Master unless someone needs it.
