### ISSUE TITLE
Release: Sep 28, 2022

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2814]

**Comment by melwong-jcc** [comment]
## SRL
[bugfix/SRL-647--index-link-translation-support](url)
- Corrects/Simplifies index link visibility logic

**Comment by baptisten** [comment]
### SRL
[fix/SRL-614-label-to-be-translated](https://github.com/chapter-three/jcc-srl/tree/fix/SRL-614-label-to-be-translated)
- Make the menu-based dropdown labels translatable for cards

**Comment by baptisten** [comment]
### SRL
[fix/SRL-614-label-to-be-translated](https://github.com/chapter-three/jcc-srl/tree/fix/SRL-614-label-to-be-translated)
- Make the menu-based dropdown labels translatable for cards

**Comment by ivanbueno-jcc** [comment]
### Trial Court

[feature/TCI-972--x-frame-options](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-972--x-frame-options)
* Allow X-Frame-Options for embedding
