### ISSUE TITLE
Release: Oct 5, 2022

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2828]
**DO NOT RESET SRL DEVELOP TO MASTER** 

## SRL
[bugfix/SRL-666--linkit-autocomplete-fix](https://github.com/chapter-three/jcc-srl/tree/bugfix/SRL-666--linkit-autocomplete-fix)
- Patches Linkit autocomplete with missing Webform matcher support

[feature/SRL-665--anchor-link-support](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-665--anchor-link-support)
- Enable anchor link/jump point feature in WYSIWYG editor

[feature/SRL-667--disable-browser-language-detection](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-667--disable-browser-language-detection)
- Disables browser language detection to manage more reliable/effective translations through Drupal

## Platform/Supreme Court
[feature/SC-370--captcha-and-honeypot](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-370--captcha-and-honeypot)
- Already updated captcha and recaptcha modules
- Configures Supreme Court to use recaptcha as default
- Courtyard v342 to fix missing global alerts that were not displaying in feedback dialog
- POST DEPLOYMENT STEP: Add recaptcha keys and add field to feedback webform
- KNOWN ISSUE: On error, the recaptcha disappears and the community is still working on a 9.x patch to correct AJAX support.

**Comment by baptisten** [comment]
### SRL
[feature/SRL-668-robotstxt-update](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-668-robotstxt-update)
- Update robots.txt
