### ISSUE TITLE
Release: Oct 12, 2022

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#2847]

**Comment by melwong-jcc** [comment]
## Supreme Court
[bugfix/SC-372--nested-section-spacing](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-372--nested-section-spacing)
- Fixes out-of-place left indent that is appearing for the body content

**Comment by sleepingmonk** [comment]
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-713--shuffle-cards
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-978--revisions-author-list-view
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/TCI-980--rename-migrated-file-duplicates
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/hotfix/TCI-976--add-user-password-field
