### ISSUE TITLE
Release: November 2, 2022

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#2873]
## Supreme Court/Platform
[bugfix/SC-374--allow-remote-images](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/SC-374--allow-remote-images)
- Allow remote images for Supreme Court's body text editor
- Limits content source editing to admin and manager if 'Restrict Images to Site' filter is disabled
- Customizes 'Restrict Images to Site' description to warn content source editing limitation

**Comment by baptisten** [comment]
### Newsroom

[fix/newsroom-custom-fields-in-rss-removal](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/newsroom-custom-fields-in-rss-removal)
- Removed RSS custom field in order to validate new service
