### ISSUE TITLE
Release : November 30th 2022 

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2886]

**Comment by baptisten** [comment]
### SRL
[feature/SRL-676-homepage-menu-order](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-676-homepage-menu-order)
- Translated menus can't be sorted independently from English menus

**Comment by baptisten** [comment]
### NEWSROOM
[feature/WSGEN-1333-newsroom-digest-from-email-update](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/WSGEN-1333-newsroom-digest-from-email-update)
- Change email on News Digest

**Comment by melwong-jcc** [comment]
## SRL
[bugfix/SRL-686--chat-banner-alt-prepend](https://github.com/chapter-three/jcc-srl/tree/bugfix/SRL-686--chat-banner-alt-prepend)
- Improves on chat promotional banner universal prepend
