### ISSUE TITLE
Release : December 07th 2022

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2897]

**Comment by baptisten** [comment]
### NEWSROOM
[fix/newsroom-her-imgs-urls](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/newsroom-her-imgs-urls)
- Hero images using URLs instead of URIs

**Comment by melwong-jcc** [comment]
## Amador
[feature/TCI-996--amador-logo](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-996--amador-logo)
- adds logo SVG to enable from admin console
