### ISSUE TITLE
Release: Feb 8, 2023

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#2957]

**Comment by archanajcc** [comment]
Trialcourt

[TCI927](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI927)

Fixed editor inconsistencies (changed _scheme_ from base to local)

**Comment by baptisten** [comment]
###TC
[feature/SC-349-deleted-files-still-in-system](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/SC-349-deleted-files-still-in-system)
- Let users clean unused files in the system, and prevents files to stick after media entity deletion.

**Comment by archanajcc** [comment]
Trialcourt

[TCI927](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI927)

Changing the scheme in config

**Comment by reshmai** [comment]
### Trialcourt
[feature/TCI-984--editor-control-request](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-984--editor-control-request)

- Subscript, superscript, strikethrough, Removeformat Editor control requests added

**Comment by reshmai** [comment]
### Trialcourt
[feature/TCI-1012--tuolumne-spanish-missing](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-1012--tuolumne-spanish-missing)

- Enabled Language switcher in toolbar 
- Spanish language added for all content translation
