### ISSUE TITLE
Early Release: March 8, 2023

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#3011]
## Trialcourts
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/site/TCI-1037--create-sanmateo
- Create and initial setup for San Mateo

**Comment by baptisten** [comment]
### TC
[feature/TCI-885-tentative-ruling-v2](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-885-tentative-ruling-v2)
- Adding structures to TC sites:
  - Content types : Judge / Tentative rulings
  - Taxonomy : Case type / Department
  - User role : Tentative ruling editor
  - View : Tentative ruling
