### ISSUE TITLE
Release May24th 2023

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3265]

**Comment by paboden** [comment]
**TrialCourt**

CSS cleanup
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3268
Branch - [fix/cleanup-of-minor-css-issues](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/cleanup-of-minor-css-issues)

**Comment by melwong-jcc** [comment]
## LAS
[feature/LWR-190--card-media-align-integration](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-190--card-media-align-integration)
- Added media alignment options
- Refactored media and background color fields as collapsible elements to for improved editing UX

**Comment by melwong-jcc** [comment]
## LAS
[feature/LWR-190--card-media-align-integration](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-190--card-media-align-integration)
- Added media alignment options
- Refactored media and background color fields as collapsible elements to for improved editing UX

**Comment by melwong-jcc** [comment]
## Newsroom
For @Ravi-jud

[NEW-38-supreme-court-stream-not-rendering-content](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/NEW-38-supreme-court-stream-not-rendering-content)
- Correcting view filter for stream Supreme Court news
