### ISSUE TITLE
Release: July 5, 2023

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#3360]

**Comment by ivanbueno-jcc** [comment]
### Trial Court

[feature/oc-site-mapping-request](https://github.com/JudicialCouncilOfCalifornia/trialcourt/compare/feature/oc-site-mapping-request)
* Adding a new domain for Orange County per their request

**Comment by archanajcc** [comment]
Trialcourt

Create Plumas
[TCI-1118-create-new-site-plumas](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1118-create-new-site-plumas)

**Comment by melwong-jcc** [comment]
## Appellate/Platform
[bugfix/DCAS-53--missing-search-api-pantheon-admin](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/DCAS-53--missing-search-api-pantheon-admin)
- Enable Search API Pantheon Admin where missing
- Installs Search API Pantheon Admin by default if using immutable

**Comment by paboden** [comment]
**TRIALCOURT/DCAS**

Update to storybook theme 0.54.4
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3379
Branch - https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/update/update-storybook-theme-to-0-54-4-plus

**Comment by Ravi-jud** [comment]
### NEWSROOM

https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3382

Added updated column to content view page

**Comment by reshmai** [comment]
### TRIALCOURT

[feature/TCI-1031--entity_autocomplete_selection_handler](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-1031--entity_autocomplete_selection_handler)

- Entity autocomplete selection handler added.
- Node filtered with published content and set limit

### SRL

[feature/SRL-716--update-robotes](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-716--update-robotes)
- robots.txt file updated
