### ISSUE TITLE
Release: July 12, 2023

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3392]

**Comment by baptisten** [comment]
### TC
[feature/LWR-235-document-re-import](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-235-document-re-import)
- Missing field in the import

**Comment by melwong-jcc** [comment]
## Diversity Toolkit
[site/RJDT-1--create-diversity-toolkit](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/site/RJDT-1--create-diversity-toolkit)
- Creates new instance for the Racial Justice Diversity Toolkit site project
- Updates gitignore with missed files from last deployment
