### ISSUE TITLE
Release: July 26, 2023

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#3431]

**Comment by archanajcc** [comment]
TRIALCOURT

[TCI-1124-create-Shasta](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1124-create-Shasta)
Create new site Shasta

**Comment by baptisten** [comment]
### LAS

[feature/LWR-258-h1-full-length-in-hangover](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-258-h1-full-length-in-hangover)
- Run Page title/H1 in hero component the full content width when there is no hangover image

**Comment by paboden** [comment]
TC/LAS/DCA

Feature -- Added "LegalFormatted List" style option to Ckeditor
PR -- https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3442
Branch -- https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-54-drupal-integrate-legal-bulleted-style

**Comment by reshmai** [comment]
### TC

[feature/TCI-1101--Hero-Image-Title](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-1101--Hero-Image-Title)

- Adding photo attribution text field for Hero banner
- Courtyard update

**Comment by melwong-jcc** [comment]
## Appellate/Platform
feature/DCAS-35--livecast-support
- Updates Granicus module to add optional view call to action for the Hero component
