### ISSUE TITLE
Release: August 16th, 2023

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3482]

**Comment by archanajcc** [comment]
TC

Allow CSV file type
[TCI-1127-allow-csv-filetype](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1127-allow-csv-filetype)

**Comment by baptisten** [comment]
### Newsroom
[feature/NEW-46-manage-subs-for-newsroom](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/NEW-46-manage-subs-for-newsroom)
- Manage subscription 403 error for newsroom

**Comment by paboden** [comment]
TC/DCA

PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3487
Branch - LWR-251-DCAS-60--primary-nav-hover-and-sb-library-update

**Includes:**
- Update to storybook library 0.54.8 -> 0.54.10
- Change primary navigation to be hover based, and remove the programmatically created Overview links from the desktop menu. Mobile menu still is tap based and still has the overview link output.
- Update to immutable feature to get code in-sync with sites
- Minor update to admin styling for section paragraph edit form (tabs and field alignment was a little off)

**Instructions:**
- Clear cache
- Run database import to trigger immutable feature revert

**Comment by paboden** [comment]
### TC/DCA

Branch - feature--ability-to-customize-settings--groundwork-for-app-embed-and-sections

This is groundwork for the App embed functionality (for things like the Map on Appellate) and for the site sections/groups functionality.

**Includes:**
- New "jcc_elevated_custom" module that sets the ground work for being able to define state settings for custom elements in the site.
- These customizations include defining navigation elements and styles, the site machine name, and helper functions.

**Comment by reshmai** [comment]
### SRL

[SRL-694--demand-letter-update](https://github.com/chapter-three/jcc-srl/tree/SRL-694--demand-letter-update)

Demand letter for security deposit

**Comment by ivanbueno-jcc** [comment]
@melwong-jcc reassigning this week's deployoment to you.  I'm unavailable during this time.  I'll handle next week's.  Thanks.
