### ISSUE TITLE
Release: October 04, 2023

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#3615]
Test Cases:
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=968044354

**Comment by baptisten** [comment]
### DCA
[feature/DCAS-117-install-trial-court-favicon-on-DCA-LAS](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/DCAS-117-install-trial-court-favicon-on-DCA-LAS)
- Install trial court favico on DCA / LAS

**Comment by melwong-jcc** [comment]
## Platform
[core/critical-9.5.11-upgrade](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/core/critical-9.5.11-upgrade)
- Upgrade core to 9.5.11 for proactive fix

## SRL
[core/critical-9.5.11-upgrade](https://github.com/chapter-three/jcc-srl/tree/core/critical-9.5.11-upgrade)
- Upgrade core to 9.5.11 for proactive fix

**Comment by ivanbueno-jcc** [comment]
### Racial Justice Toolkit

[feature/RJDT-2--diversity-dns](https://github.com/JudicialCouncilOfCalifornia/trialcourt/compare/feature/RJDT-2--diversity-dns)
* Set domain name to the instance

**Comment by archanajcc** [comment]
TC
Create Marin
https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI1161-marin

**Comment by paboden** [comment]
### ELEVATED

**DCAS-132 - Hide alert nodes (full/default display) from anonymous viewers**
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3630
branch - [DCAS-132-hiding-alert-nodes](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-132-hiding-alert-nodes)

Test: Visit an alert node directly as a logged in user and as anonymous visitor, and confirm that only logged in users can directly view an alert node.

**Comment by paboden** [comment]
### ELEVATED

**Feature- Improved content moderation form for elevated theme (frontend)**
PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3631
branch - [feature/better-style-for-moderation-form-on-frontend](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/better-style-for-moderation-form-on-frontend)
