### ISSUE TITLE
Release: October 25, 2023 

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3682]
Smoke Test Plan
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=1228482566

Feature/Bug fix tests may be documented in the Jira ticket linked from the test plan if needed.

**Comment by melwong-jcc** [comment]
## LAS
[bugfix/DCAS-163--publication-upload-issues](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/DCAS-163--publication-upload-issues)
- Corrects translated publication files query
- Adds additional file types allowed for East Armenian translated publication

**Comment by reshmai** [comment]
## SRL
[feature/SRL-712--add-share-icons](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-712--add-share-icons)

- Added share icons to Basic pages and Onramp pages

**Comment by paboden** [comment]
### Elevated

PR - https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/3693
[DCAS-161-possible-caching-issue-with-justices](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-161-possible-caching-issue-with-justices)

- This change removes tagged based caching on the view. There is field and node level caching that prevents the view from updating with arguments.

Testing:
- Visit several Judge pages in the districts, and confirm that it is displaying proper content.
- (Make sure that caches are cleared just in case)

**Comment by paboden** [comment]
### Elevated

DCAS-128-left-nav-showing-too-many-pages
Setup the sidebar nav to adjust its height depending on available space.
