### ISSUE TITLE
Release: November 8, 2023 (PHP 8 Upgrade - SRL)

### ISSUE THREAD

**Issue by melwong-jcc** [JudicialCouncilOfCalifornia/trialcourt#3686]
Only the PHP 8 upgrade will be deployed for SRL.
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=1160147880

**Comment by archanajcc** [comment]
## SRL

PHP8 upgrade
[php8-upgrade](https://github.com/chapter-three/jcc-srl/tree/php8-upgrade)

**Comment by archanajcc** [comment]
## SRL

PHP upgrade
[[php8-upgrade](https://github.com/chapter-three/jcc-srl/tree/php8-upgrade)]
