### ISSUE TITLE
Release: January 24, 2024

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3911]
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=572440988

**Comment by archanajcc** [comment]
Newsroom:

[NEW-76](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/NEW-76)
- Promotional image language

**Comment by baptisten** [comment]
### DCAS

[feature/DCAS-210-publication-link-to-file](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/DCAS-210-publication-link-to-file)
- Publications: When choosing to link to a publication, offer the author an option to choose to link directly to the asset or to the node


[feature/DCAS-189-remove-to-and-from-filter-for-publications](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/DCAS-189-remove-to-and-from-filter-for-publications)
- LAS: Remove To and From Filter for Publications
