### ISSUE TITLE
Release: February 7, 2024

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#3930]
https://docs.google.com/spreadsheets/d/10nfRnx2lfYmvpeIfDQaQD2Qe1dfBIjLW42yKEDQFXqc/edit#gid=387016467

**Comment by melwong-jcc** [comment]
## SRL
https://github.com/chapter-three/jcc-srl/tree/feature/SRL-755--default-en-if-lang-variant-not-ready
- Main menu defaults to English content if translation status is not "Published"

**Comment by baptisten** [comment]
### SRL

[feature/SRL-760-robotstxt-update](https://github.com/chapter-three/jcc-srl/tree/feature/SRL-760-robotstxt-update)
- Remote Robots.txt protection and update sitemap.xml

**Comment by paboden** [comment]
### TrialCourt/Platform

[DCAS-244--change-date-format](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-244--change-date-format)
- Set the "M d, Y" date format, which was outputting as "Jan 01, 2000" (M d, Y) style to output as "January 1, 2000" (F j, Y) style.
- Updated the format type in the immutable feature, and updated some preprocess/templates to use the `F j, Y` style

**Comment by archanajcc** [comment]
### DCA

[DCAS-232-alt-image-justices](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/DCAS-232-alt-image-justices)
- Alt images for justices
