### ISSUE TITLE
Release: April 24, 2024

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#4120]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=eOmf4S&nav=MTVfezA1NjVDMjZDLTdCNjAtNDkyNy1CN0YxLTBGNzQ2MkJBNjQ4NH0

**Comment by paboden** [comment]
###COURTS

[COURTS-11] -- Rules of Court Setup

**PENDING - this might go in this release, if everyone approves, but very possible it will hold until May release** 

Contains a standalone feature, with new content types, paragraph types, views, and additional settings for the Rules of Court setup. Contains a custom module that will only be enabled on courts.ca.gov website. Contains a CSV based migration for Rule documents and Rule subsections. Some manual setup needs to be done on release.

PR: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4111
Branch: [COURTS-11--rules-of-court--feature-and-content-node-based](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-11--rules-of-court--feature-and-content-node-based)

**Comment by melwong-jcc** [comment]
## Elevated
[feature/LWR-284--google-translate](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/LWR-284--google-translate)
- Adds foundation for translation feature including Google Translate if still allowed to use
- Updates to Storybook v0.55.27

**Comment by adityajoshi94** [comment]
Newsroom

Ticket : [feature/News-97-duplicative-title-upcoming-pager/](https://judasdg.atlassian.net/browse/NEW-97)
Branch: https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/News-97-duplicative-title-upcoming-page

Ticket : [feature/Newsroom-87-newslink-ready-not-archiving/](https://judasdg.atlassian.net/browse/NEW-86)
Branch: https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/Newsroom-87-newslink-ready-not-archiving
