### ISSUE TITLE
Release, July 31st, 2024

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#4362]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=m9kAtv&nav=MTVfezIzMTAzNDcyLTg1RDAtNDZGMS1BQ0RDLTU0NDIyOTYwNDcwRn0&ovuser=10cfa08a-5b17-4e8f-a245-139062e839dc%2CMel.Wong%40jud.ca.gov&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNDA0MTEyMjMxNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

**Comment by baptisten** [comment]
### Courts

[feature/COURTS-126-rfp-unpublished-access](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-126-rfp-unpublished-access)
- Temporary Unpublished Access Not Working on Elevated

**Comment by paboden** [comment]
### Courts/Elevated

[COURTS-39] - Solicitation request UI improvements, Field changes, admin improvements, etc...
PR: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4191
Branch: [COURTS-39--rfp-migration-and-admin-improvements](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-39--rfp-migration-and-admin-improvements)

**Comment by paboden** [comment]
### Courts/Elevated
[Update] - Programmatically set access unpublished settings for rules of court
PR: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4191
Branch: [update/programmatically-set-access-unpublished-settings-for-roc](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/update/programmatically-set-access-unpublished-settings-for-roc)
