### ISSUE TITLE
Release: September 18 2024 (POSTPONED)

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#4504]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=m9kAtv&nav=MTVfezIzMTAzNDcyLTg1RDAtNDZGMS1BQ0RDLTU0NDIyOTYwNDcwRn0&ovuser=10cfa08a-5b17-4e8f-a245-139062e839dc%2CMel.Wong%40jud.ca.gov&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI1MC8yNDA2MTMxODQxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

**Comment by baptisten** [comment]
### COURTS
[feature/updates-resources-for-ab](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/updates-resources-for-ab)
- Missing tab for AB

**Comment by melwong-jcc** [comment]
## Legacy Courts
Add server rewrite rule to redirect visitors to Rules of Court new location

**Comment by paboden** [comment]
### Elevated

[StoryBook Update and COURTS-230]
Update to Storybook for last little cleanup and tweaks after header, navigation, mobile, and footer updates. Also includes fix to body component leads -- https://judasdg.atlassian.net/browse/COURTS-230
**Branch:** update/storybook-update-including-COURTS-230-body-fix
