### ISSUE TITLE
Release: October 9, 2024

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#4559]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=0N1V8l&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wRDAwLTAwMDAwMDAwMDAwMH0

**Comment by baptisten** [comment]
### COURTS
[advisory_body_event_excerpts](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/advisory_body_event_excerpts)
- Fixes event's excerpts for advisory bodies

**Comment by melwong-jcc** [comment]
## Elevated
[feature/COURTS-146--node-default-paragraphs](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-146--node-default-paragraphs)
- Programmatically set multiple components as defaults for landing pages and subpages, non-elevated sites uneffected

**Comment by ivanbueno-jcc** [comment]
### Trial Court

[bugfix/oc-export-config-azure](https://github.com/JudicialCouncilOfCalifornia/trialcourt/compare/master...bugfix/oc-export-config-azure)
* Export Orange County's Azure AD settings to config.

**Comment by paboden** [comment]
### Elevated

**[COURTS-239]**
Update event field label to "Webcast"
**PR:** https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4584
**Branch:** [update/COURTS-239--change-event-field-label-to-webcast](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/update/COURTS-239--change-event-field-label-to-webcast)

---------

**[COURTS-252]**
Fix children output for menus and style updates for footer lower nav
**PR:** https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4582
**Branch:** [fix/COURTS-252--footer-lower-nav-children-render-fix](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/COURTS-252--footer-lower-nav-children-render-fix)

**Comment by archanajcc** [comment]
COURTS

**Comment by Ravi-jud** [comment]
### Trialcourts

[TCI-12360-adding-arbitrator-view-solano](https://judasdg.atlassian.net/browse/TCI-1260)

Adding arbitrator view for solano

T[CI-1236-Adding-search-field-for-arbitrator-content-view](https://judasdg.atlassian.net/browse/TCI-1236)

Adding search field to filter data once view is embedded in a page

**Comment by Ravi-jud** [comment]
> ### Trialcourts
> T[CI-1236-Adding-search-field-for-arbitrator-content-view](https://judasdg.atlassian.net/browse/TCI-1236) **(POSTPONE)**
> 
> Adding search field to filter data once view is embedded in a page

**Comment by Ravi-jud** [comment]
> > ### Trialcourts
> > T[CI-1236-Adding-search-field-for-arbitrator-content-view](https://judasdg.atlassian.net/browse/TCI-1236) **(POSTPONE)**
> > Adding search field to filter data once view is embedded in a page

**DO NOT MERGE**
