### ISSUE TITLE
Release: October 23,2024

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#4633]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=Dhb6cT&nav=MTVfe0MxMzQ3MUJFLTBCN0UtNDBFQy05QTU0LUE5NDc3Qjg5RDJDNn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1729553386180&web=1

**Comment by Ravi-jud** [comment]
### Trialcourt

[TCI-1184-Reverting-supreme-court-logo](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1184-supremecourt-logo-update)

**Comment by ivanbueno-jcc** [comment]
### Courts

[feature/COURTS-70--migrate-policy-profiles-pages](https://github.com/JudicialCouncilOfCalifornia/trialcourt/compare/master...feature/COURTS-70--migrate-policy-profiles-pages)
* Migrate Policy/Admin pages and bios.

**Comment by archanajcc** [comment]
**COURTS**
Add gifs
[COURTS-255-add-gifs](https://github.com/JudicialCouncilOfCalifornia/trialcourt/commit/c185b9e75bed47f6bc6c905d05ca7e057bb186ab)

**Comment by baptisten** [comment]
### COURTS

[fix/COURTS-159-empty-mobile-version](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/COURTS-159-empty-mobile-version)
- Fixed empty mobile width/height

**Comment by paboden** [comment]
### Elevated

[COURTS-229]
Feature: Deep Linking to tabs (Advisory bodies and others)
Branch: feature/COURTS-229--deep-linking-tabs--query-attribute-based

---------

[COURTS-268]
RFP warnings when ckeditor accessing media library
Branch: fix/COURTS-268--rfp-solicitations-form-alter-php-warning-fix

---------

[COURTS-256]
Drupal: Cannot link images
Branch: feature/COURTS-256--drupal-ckeditor-apply-link-to-media-embeds

---------

[COURTS-261]
Undefined rules_manager warning appearing for multiple sites
Branch: fix/COURTS-261--undefined-php-warning-nodeaccess-config-role-rules-manager
