### ISSUE TITLE
Release: November 6, 2024

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#4652]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=Dhb6cT&nav=MTVfe0MxMzQ3MUJFLTBCN0UtNDBFQy05QTU0LUE5NDc3Qjg5RDJDNn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1729553386180&web=1

**Comment by baptisten** [comment]
### COURTS

[feature/COURTS-225-links-to-edit-events](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-225-links-to-edit-events)
- Add create/edit links to events

**Comment by melwong-jcc** [comment]
## Elevated

feature/COURTS-210-211--mega-hero-and-updated-card-theme
- Storybook 0.57.x - Updates default card as new standard, section, hero, hero hangover, lists, and any related related components
- Adjusts integration with Storybook updates
- Adds mega hero to Drupal
- Adds grouping option to improve on Layout Section more than 2 components layout support, specifically sidebar use
- Fixes grid display CSS incompatibility and older iOS versions

**Comment by paboden** [comment]
### TrialCourts/Elevated

[COURTS-261]
Undefined rules_manager warning appearing for multiple sites
Branch: fix/COURTS-261--undefined-php-warning-nodeaccess-config-role-rules-manager

**This might get delayed depending on if the nodeaccess module is still actually functioning properly for all sites. Testing is still underway to see if this task will change.
Initial testing locally shows that it might not be blocking content by permissions, so the patch to hide the php notices/warnings would be irrelevant.**

**Comment by archanajcc** [comment]
### COURTS

Popular links
[COURTS-215-popular-links](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-215-popular-links)

Search Console Verification
[COURTS-251-add-metatag](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-251-add-metatag)

**Comment by ivanbueno-jcc** [comment]
# Courts

[feature/COURTS-243--search-add-content](https://github.com/JudicialCouncilOfCalifornia/trialcourt/compare/master...feature/COURTS-243--search-add-content)
* Enhance search.  Index more content types.  Add stopwords.  Rearrange processors.

**Comment by paboden** [comment]
### Elevated

[COURTS-269]
Add flickr to footer social media section.
PR: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4699
Branch: [feature/COURTS-269--add-flickr-to-social-media-footer-section](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-269--add-flickr-to-social-media-footer-section)

**Comment by Ravi-jud** [comment]
### SRL

[SRL-812-Banner-for-appellate-self-help](https://github.com/chapter-three/jcc-srl/tree/SRL-812-Banner-for-appellate-self-help)

Adding banner ability for appeals taxonomy term

### NEWSROOM

[NEW-111-Supreme-court-oral-argument-url](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/NEW-111-Supreme-court-oral-argument-url)

Added supreme court oral argument link to the calendar page

### TRIALCOURTS

[TCI-1236-Arbitrator-search-fields-display](https://judasdg.atlassian.net/browse/TCI-1236)

Adding search ability for arbitrator view
