### ISSUE TITLE
Release: November 13th, 2024

### ISSUE THREAD

**Issue by baptisten** [JudicialCouncilOfCalifornia/trialcourt#4679]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=Dhb6cT&nav=MTVfe0MxMzQ3MUJFLTBCN0UtNDBFQy05QTU0LUE5NDc3Qjg5RDJDNn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1729553386180&web=1

**Comment by baptisten** [comment]
### NEWSROOM

[fix/NEW-110-subbscription-manager](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/fix/NEW-110-subbscription-manager)
- Bypass the token workflow for logged in users
- Deprecated functions cleanup

**Comment by melwong-jcc** [comment]
## Elevated
[feature/TCI-1273--persistent-drawer](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/TCI-1273--persistent-drawer)
- Making drawer container persistent for non-Drupal widget integrations - already persistent for trial courts

**Comment by baptisten** [comment]
### COURTS

[feature/COURTS-234-solicitation-view-update](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-234-solicitation-view-update)
- Reverse-chronological order for Requests
- Items per page filter

**Comment by alexwu-jcc** [comment]
COURTS

[feature/tci-1268](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/tci-1268)

- Hide away the "Create new account" tab and its associated panel for all the court sites except newsroom and superior courts, for non admin users.

**Comment by paboden** [comment]
### All

**[COURTS-258] -- Module updates**
Only updates that are generally simple or don't require any updates or configuration changes.
**PR**: [COURTS-258](https://judasdg.atlassian.net/browse/COURTS-258)
**Branch**: update/COURTS-258-drupal-module-updates-nov-2024

**Comment by archanajcc** [comment]
## COURTS
[COURTS-272-news-feed](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-272-news-feed)
- News feed from Newsroom
