### ISSUE TITLE
Release: November 20th, 2024

### ISSUE THREAD

**Issue by archanajcc** [JudicialCouncilOfCalifornia/trialcourt#4720]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=Dhb6cT&nav=MTVfe0MxMzQ3MUJFLTBCN0UtNDBFQy05QTU0LUE5NDc3Qjg5RDJDNn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1729553386180&web=1

**Comment by paboden** [comment]
### All

**[COURTS-258] -- Module updates**
Only updates that are generally simple or don't require many updates or configuration changes.
**PR**: [COURTS-258](https://judasdg.atlassian.net/browse/COURTS-258)
**Branch**: [update/COURTS-258-drupal-module-updates-nov-2024](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/update/COURTS-258-drupal-module-updates-nov-2024)

**Comment by archanajcc** [comment]
## Courts
[COURTS-272-news-feed](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/COURTS-272-news-feed)
- News feed from Newsroom

**Comment by baptisten** [comment]
### COURTS

[feature/COURTS-277-spacing-tunning](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/COURTS-277-spacing-tunning)
- Adjusting spacing

**Comment by Ravi-jud** [comment]
### Trialcourt

[TCI-1266-Hide-add-column0to-court-calendar](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/TCI-1266-Hide-add-column0to-court-calendar)

removing columns if they are empty and also added cache to the page

**Comment by melwong-jcc** [comment]
## Elevated
[bugfix/COURTS-297--content-stream-blocking-page-save](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/bugfix/COURTS-297--content-stream-blocking-page-save)
- Restores missing section option that is preventing pages from saving
