### ISSUE TITLE
Release: Dec 11, 2024

### ISSUE THREAD

**Issue by ivanbueno-jcc** [JudicialCouncilOfCalifornia/trialcourt#4813]
https://caljc.sharepoint.com/:x:/s/WebServices2/ERqCTfoNfDVIgv8Pg_xGMFoBRpCZ00xbvs67cE5ix1WNrA?e=Dhb6cT&nav=MTVfe0MxMzQ3MUJFLTBCN0UtNDBFQy05QTU0LUE5NDc3Qjg5RDJDNn0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1729553386180&web=1

**Comment by melwong-jcc** [comment]
## Elevated

Rewrite rule fixes and updates for www4 utilization and redirects to phase 2 migrated content

**Comment by archanajcc** [comment]
News date fix, SB update
 [COURTS-news-fix](https://app.circleci.com/pipelines/github/JudicialCouncilOfCalifornia/trialcourt?branch=COURTS-news-fix)

**Comment by baptisten** [comment]
### COURTS
[feature/fmc-title-update](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/feature/fmc-title-update)
- Title update

**Comment by paboden** [comment]
### ALL

**[COURTS-312]**
Module updates - Round 1
**PR**: https://github.com/JudicialCouncilOfCalifornia/trialcourt/pull/4819
**Branch**: [update/COURTS-321--module-updates--round-1](https://github.com/JudicialCouncilOfCalifornia/trialcourt/tree/update/COURTS-321--module-updates--round-1)

**Comment by paboden** [comment]
### ELEVATED

**[COURTS-305]**
File Name When Downloading Files
**Branch**: feature/COURTS-305--auto-set-file-name-when-downloading-file
